"""Add envelope encryption fields

Revision ID: 1a2b3c4d5e6f
Revises: a1b2c3d4e5f6
Create Date: 2025-08-11 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to identity_embeddings
    op.add_column('identity_embeddings', sa.Column('encrypted_dek', sa.LargeBinary(), nullable=True))
    op.add_column('identity_embeddings', sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Add encryption columns to evidence table (created by create_all)
    op.add_column('evidence', sa.Column('encrypted_dek', sa.LargeBinary(), nullable=True))
    op.add_column('evidence', sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Add encryption columns to snapshots table (created by create_all)
    op.add_column('snapshots', sa.Column('encrypted_dek', sa.LargeBinary(), nullable=True))
    op.add_column('snapshots', sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove encryption columns from snapshots
    op.drop_column('snapshots', 'is_encrypted')
    op.drop_column('snapshots', 'encrypted_dek')

    # Remove encryption columns from evidence
    op.drop_column('evidence', 'is_encrypted')
    op.drop_column('evidence', 'encrypted_dek')

    # Remove encryption columns from identity_embeddings
    op.drop_column('identity_embeddings', 'is_encrypted')
    op.drop_column('identity_embeddings', 'encrypted_dek')
    # ### end Alembic commands ###
