"""Gen5 Upgrade

Revision ID: 9c8d7e6f5a4b
Revises: 7d48f1b2c3a0
Create Date: 2025-08-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9c8d7e6f5a4b'
down_revision = '7d48f1b2c3a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Blockchain Evidence Ledger
    op.create_table('blockchain_ledger',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('evidence_hash', sa.String(length=64), nullable=False),
        sa.Column('transaction_hash', sa.String(length=66), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('metadata', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('evidence_hash'),
        sa.UniqueConstraint('transaction_hash')
    )
    op.create_index(op.f('ix_blockchain_ledger_id'), 'blockchain_ledger', ['id'], unique=False)

    # 2. Predictive Policing & Bias Mitigation
    op.create_table('predictive_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('prediction_type', sa.String(), nullable=False), # e.g., 'hotspot', 'reappearance'
        sa.Column('prediction_data', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('bias_score', sa.Float(), nullable=True),
        sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('auditor_id', sa.String(), nullable=True),
        sa.Column('audit_status', sa.String(), nullable=True), # 'approved', 'rejected'
        sa.Column('audit_notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictive_logs_id'), 'predictive_logs', ['id'], unique=False)

    # 3. Case Management & Unified Suspect Profile
    op.create_table('cases',
        sa.Column('id', sa.String(), nullable=False), # UUID
        sa.Column('case_number', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False), # 'open', 'closed', 'cold'
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('case_number')
    )

    op.create_table('suspect_profiles',
        sa.Column('id', sa.String(), nullable=False), # UUID
        sa.Column('identity_id', sa.String(), nullable=True), # Link to existing identity_embeddings
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('aliases', sa.Text(), nullable=True),
        sa.Column('threat_level', sa.Float(), nullable=True),
        sa.Column('profile_summary', sa.Text(), nullable=True), # AI-generated
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('case_evidence_link',
        sa.Column('case_id', sa.String(), nullable=False),
        sa.Column('evidence_id', sa.String(), nullable=False), # Can be snapshot_id, multimodal_evidence_id, etc.
        sa.Column('evidence_type', sa.String(), nullable=False), # 'snapshot', 'audio', 'text_report'
        sa.Column('correlation_score', sa.Float(), nullable=True),
        sa.Column('linked_by', sa.String(), nullable=False), # 'agent' or user_id
        sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
        sa.PrimaryKeyConstraint('case_id', 'evidence_id')
    )

    op.create_table('case_suspect_link',
        sa.Column('case_id', sa.String(), nullable=False),
        sa.Column('suspect_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
        sa.ForeignKeyConstraint(['suspect_id'], ['suspect_profiles.id'], ),
        sa.PrimaryKeyConstraint('case_id', 'suspect_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_suspect_link')
    op.drop_table('case_evidence_link')
    op.drop_table('suspect_profiles')
    op.drop_table('cases')
    op.drop_index(op.f('ix_predictive_logs_id'), table_name='predictive_logs')
    op.drop_table('predictive_logs')
    op.drop_index(op.f('ix_blockchain_ledger_id'), table_name='blockchain_ledger')
    op.drop_table('blockchain_ledger')
    # ### end Alembic commands ###
